### ISSUE TITLE
Error running md-mapper

### ISSUE THREAD

**Issue by borsna** [TheLanguageArchive/md-mapper#3]
There is no clear instructions of how to run the compiled mapper.
By looking at the source code i think this command is correct(?)

```
java -jar md-mapper/target/md-mapper-0.1.a8ac39.jar config=/home/olof/5.4/config.xml
```

I have checked out the md-mapper and md-mapping where i also have some mapping examples.
config.xml contains:

```
<?xml version="1.0" encoding="UTF-8" ?>
<config>
  <!-- Parameters: any of these can be overridden via the command line. -->
  <params>
    <mapfile>/home/olof/5.4/md-mapping/mapfiles/cmdi.xml</mapfile>
    <inputdir>/home/olof/5.4/md-mapping/testfiles/cmdi</inputdir>
    <savestats>/home/olof/5.4/stats.log</savestats>
    <!-- The parameter <outputdir>x</outputdir> can be used to set x
         as the base directory against which directories in the
         outputs section below are resolved.  -->
  </params>

  <!--
      Outputs: the directory name is given in the text content. An
      empty tag means output to stdout instead of a file.
  -->
  <outputs>
    <!-- <output type="simplejson" prettyPrint="true">json-simple</output> -->
    <!-- <output type="xml" prettyPrint="true">xml</output> -->
    <output type="ckan3json" prettyPrint="true">json</output>
  </outputs>
</config>
```

I tried to have relative and full path for <savestats>
The error when i run the mapper is:

```
[olof@k2 5.4]$ java -jar md-mapper/target/md-mapper-0.1.a8ac39.jar config=/home/olof/5.4/config.xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at nl.mpi.mdmapper.Main.<clinit>(Main.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more
```

The build reported a successful build and `log4j-1.2.17.jar` is located in `/home/olof/5.4/md-mapper/target/lib`

Any suggestions of things to try to get the md-mapper running?

(A feature suggestion would be some default help text when running and detailed error messages.)

**Comment by kjvandelooij** [comment]
Hi Olof,

once the builds works, in the target directory you will find the package. With the mapping files in place - they need to be fetched from the DASISH repository - you can run the script. Configuration is done by editing the config.xml file.

Greetings, kj

On Mon, 4 Aug 2014 17:25:07 +0200
Olof Olsson notifications@github.com wrote:

> There is no clear instructions of how to run the compiled mapper.
> By looking at the source code i think this command is correct(?)java
> -jar md-mapper/target/md-mapper-0.1.a8ac39.jar
> config=/home/olof/5.4/config.xml
> 
> I have checked out the md-mapper and md-mapping where i also have
> some mapping examples. config.xml contains:<?xml version="1.0"
> encoding="UTF-8" ?> <config>
>    <params>
>     <mapfile>/home/olof/5.4/md-mapper/mapfiles/cmdi.xml</mapfile>
>     <inputdir>/home/olof/5.4/md-mapper/testfiles/cmdi</inputdir>
>     <savestats>/home/olof/5.3/stats.log</savestats>
>     
>   </params>
> 
>   
>   <outputs>
>       <output type="ckan3json"
> prettyPrint="true">json</output> </outputs>
> </config>
> 
> I tried to have relative and full path for
> The error when i run the mapper is:[olof@k2 5.4]$ java -jar
> md-mapper/target/md-mapper-0.1.a8ac39.jar
> config=/home/olof/5.4/config.xml Exception in thread "main"
> java.lang.NoClassDefFoundError: org/apache/log4j/Logger at
> nl.mpi.mdmapper.Main.<clinit>(Main.java:37) Caused by:
> java.lang.ClassNotFoundException: org.apache.log4j.Logger at
> java.net.URLClassLoader$1.run(URLClassLoader.java:366) at
> java.net.URLClassLoader$1.run(URLClassLoader.java:355) at
> java.security.AccessController.doPrivileged(Native Method) at
> java.net.URLClassLoader.findClass(URLClassLoader.java:354) at
> java.lang.ClassLoader.loadClass(ClassLoader.java:425) at
> sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at
> java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 1 more
> 
> The build reported a successful build and log4j-1.2.17.jar is located
> in /home/olof/5.4/md-mapper/target/lib
> 
> Any suggestions of things to try to get the md-mapper running?
> 
> (A feature suggestion would be some default help text when running
> and detailed error messages.)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
Hi Kees Jan,
I have set up a directory of example files: https://github.com/DASISH/md-mapping/tree/master/testfiles to be able to run smaller tests with the mappings in the repo.
These are located in the directory i pointed the config to as i described in my first message.
The application was successfuly build but there seams to be something wrong with log4j:

```
[olof@k2 5.4]$ java -jar md-mapper/target/md-mapper-0.1.a8ac39.jar config=/home/olof/5.4/config.xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at nl.mpi.mdmapper.Main.<clinit>(Main.java:37)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more
```

As i mention before `log4j-1.2.17.jar` is located in the `md-mapper/target/lib` but is reported as missing by the thrown exception. Is there something wrong in the way the application loads this library?

**Comment by borsna** [comment]
Full log of the build:

```
[olof@k2 md-mapper]$ mvn clean package assembly:assembly
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Mapper 0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ md-mapper ---
[INFO] Deleting /home/olof/5.4/md-mapper/target
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create (default) @ md-mapper ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] ShortRevision tag detected. The value is '6'.
[INFO] Executing: /bin/sh -c cd /home/olof/5.4/md-mapper && git rev-parse --verify --short=6 HEAD
[INFO] Working directory: /home/olof/5.4/md-mapper
[INFO] Storing buildNumber: a8ac39 at timestamp: 1407227801619
[INFO] ShortRevision tag detected. The value is '6'.
[INFO] Executing: /bin/sh -c cd /home/olof/5.4/md-mapper && git rev-parse --verify --short=6 HEAD
[INFO] Working directory: /home/olof/5.4/md-mapper
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ md-mapper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ md-mapper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to /home/olof/5.4/md-mapper/target/classes
[WARNING] /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java: /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java uses unchecked or unsafe operations.
[WARNING] /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ md-mapper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/olof/5.4/md-mapper/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ md-mapper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/olof/5.4/md-mapper/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ md-mapper ---
[INFO] Surefire report directory: /home/olof/5.4/md-mapper/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.mpi.mdmapper.NSContextTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.472 sec
Running nl.mpi.mdmapper.StringMappingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.1:jar (default-jar) @ md-mapper ---
[INFO] Building jar: /home/olof/5.4/md-mapper/target/md-mapper-0.1.a8ac39.jar
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (copy-dependencies) @ md-mapper ---
[INFO] Copying log4j-1.2.17.jar to /home/olof/5.4/md-mapper/target/lib/log4j-1.2.17.jar
[INFO] Copying junit-4.10.jar to /home/olof/5.4/md-mapper/target/lib/junit-4.10.jar
[INFO] Copying Saxon-HE-9.5.1-4.jar to /home/olof/5.4/md-mapper/target/lib/Saxon-HE-9.5.1-4.jar
[INFO] Copying gson-2.2.4.jar to /home/olof/5.4/md-mapper/target/lib/gson-2.2.4.jar
[INFO] Copying hamcrest-core-1.1.jar to /home/olof/5.4/md-mapper/target/lib/hamcrest-core-1.1.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Mapper 0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) @ md-mapper >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create (default) @ md-mapper ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] ShortRevision tag detected. The value is '6'.
[INFO] Executing: /bin/sh -c cd /home/olof/5.4/md-mapper && git rev-parse --verify --short=6 HEAD
[INFO] Working directory: /home/olof/5.4/md-mapper
[INFO] Storing buildNumber: a8ac39 at timestamp: 1407227816500
[INFO] ShortRevision tag detected. The value is '6'.
[INFO] Executing: /bin/sh -c cd /home/olof/5.4/md-mapper && git rev-parse --verify --short=6 HEAD
[INFO] Working directory: /home/olof/5.4/md-mapper
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ md-mapper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ md-mapper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to /home/olof/5.4/md-mapper/target/classes
[WARNING] /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java: /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java uses unchecked or unsafe operations.
[WARNING] /home/olof/5.4/md-mapper/src/main/java/nl/mpi/mdmapper/output/Ckan3JsonOutput.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ md-mapper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/olof/5.4/md-mapper/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ md-mapper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/olof/5.4/md-mapper/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ md-mapper ---
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO]
[INFO] --- maven-jar-plugin:2.1:jar (default-jar) @ md-mapper ---
[INFO] Building jar: /home/olof/5.4/md-mapper/target/md-mapper-0.1.a8ac39.jar
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (copy-dependencies) @ md-mapper ---
[INFO] Copying log4j-1.2.17.jar to /home/olof/5.4/md-mapper/target/lib/log4j-1.2.17.jar
[INFO] Copying junit-4.10.jar to /home/olof/5.4/md-mapper/target/lib/junit-4.10.jar
[INFO] Copying Saxon-HE-9.5.1-4.jar to /home/olof/5.4/md-mapper/target/lib/Saxon-HE-9.5.1-4.jar
[INFO] Copying gson-2.2.4.jar to /home/olof/5.4/md-mapper/target/lib/gson-2.2.4.jar
[INFO] Copying hamcrest-core-1.1.jar to /home/olof/5.4/md-mapper/target/lib/hamcrest-core-1.1.jar
[INFO]
[INFO] <<< maven-assembly-plugin:2.4:assembly (default-cli) @ md-mapper <<<
[INFO]
[INFO] --- maven-assembly-plugin:2.4:assembly (default-cli) @ md-mapper ---
[INFO] Reading assembly descriptor: package.xml
[INFO] No files selected for line-ending conversion or filtering. Skipping: /home/olof/5.4/md-mapper
[INFO] Building tar: /home/olof/5.4/md-mapper/target/md-mapper-0.1.a8ac39.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.901s
[INFO] Finished at: Tue Aug 05 10:37:00 CEST 2014
[INFO] Final Memory: 20M/246M
[INFO] ------------------------------------------------------------------------
```

**Comment by kjvandelooij** [comment]
Hi Olof, 

for this issue the same question would apply: have you run the mapper from the package. Please let me know.

Greetings, once again,

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by kjvandelooij** [comment]
Hi Olof, 

actually, this looks good. 

There should be a package around. 

Greetings, 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
As i mentioned in #2 i get the same error when i unpack the package and run it via `run-mapper.sh`
Here is a copy of the compiled package:
https://dl.dropboxusercontent.com/u/37711156/DASISH/5.4/md-mapper-0.1.a8ac39.tar.gz

**Comment by kjvandelooij** [comment]
Hi Olof,

that's very strange. Here is the output of my mvn -v

Apache Maven 2.2.1 (rdebian-8)
Java version: 1.7.0_45
Java home: /opt/jdk1.7.0_45/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux" version: "3.5.0-54-generic" arch: "amd64" Family: "unix"

Your values should resemble this. Have a look at the Java version and the Java home. The next thing I did is: clone the mapper from github. After that I applied the mvn command as listed in the README section of GitHub. This builds the package. I then installed the package and ran the mapper. Without problems.

Maybe the cloning step is the issue here.

Hope this helps.

Greetings, kj

p.s. Unfortunately, the next few days I will not be in the office. I will try to answer as much messages as possible.

On Wed, 6 Aug 2014 10:13:58 +0200
Olof Olsson notifications@github.com wrote:

> As i mentioned in #2 i get the same error when i unpack the package
> and run it via run-mapper.sh Here is a copy of the compiled package:
> https://dl.dropboxusercontent.com/u/37711156/DASISH/5.4/md-mapper-0.1.a8ac39.tar.gz
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
Hi Kees Jan,
I dont think this is dependent of the java version (I am running the same version as you).
Did some testing and I think i found the problem.
The classpath for the libraries (like log4j) is not set correctly in the jar-file manifest.
I got i working by running the jar with the libraris in the classpath:

```
[olof@k2 md-mapper-0.1.a8ac39]$ java -classpath .:md-mapper-0.1.a8ac39.jar:lib/gson-2.2.4.jar:lib/hamcrest-core-1.1.jar:junit-4.10.jar:lib/log4j-1.2.17.jar:lib/Saxon-HE-9.5.1-4.jar nl.mpi.mdmapper.Main config=/home/olof/5.4/config.xml
14:04:31,343 INFO  Main - Processing files in /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2.
14:04:31,475 INFO  FileProcessor - Processing: /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2/SND0963-001.xml
14:04:32,039 INFO  FileProcessor - Processing: /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2/SND0921-001.xml
14:04:32,425 INFO  Main - 2 records mapped; 0 records caused error(s).
```

On your system your classpath should already have these globaly but I think in this build these included libraries should be included via the classpath in the jar-file manifest?
Can you fix the compile so the jar manifest have the correct classpath?

Best regards,
Olof

**Comment by larilampen** [comment]
Hi Olof (and KJ), here's one more piece of advice from the sidelines.

You are right about the classpath being the cause. The reason it works for KJ but not for you is your different version of **Maven**. The jar plugin has been changed between Maven 2 and Maven 3. The run-mapper script adds all the jar files in lib/ to the classpath manually, so it works as long as the manifest contains the two entries `.` and `md-mapper-0.1.a8ac39.jar`, which it does if you build with Maven 2.2 but does not when using Maven >= 3.

Probably the best idea would be to target Maven 3 from now on, and to make the pom file set the manifest with all the relevant jar files so that none of that is done in the script. But of course that's for you guys, especially KJ, to decide.

**Comment by kjvandelooij** [comment]
Hi Olof,

I am happy that you sorted out the issue. I don't usually work with classpaths. Because of versioning and such, I rely on Git or SVN. The package I created from Git works, so maybe you could check if it does in your case. The advantage would be that no changes would be needed, and that is welcome since time is very scarce around here.

Greetings, and good luck, kj

On Wed, 6 Aug 2014 14:13:04 +0200
Olof Olsson notifications@github.com wrote:

> Hi Kees Jan,
> I dont think this is dependent of the java version (I am running the
> same version as you). Did some testing and I think i found the
> problem. The classpath for the libraries (like log4j) is not set
> correctly in the jar-file manifest. I got i working by running the
> jar with the libraris in the classpath:[olof@k2
> md-mapper-0.1.a8ac39]$ java
> -classpath .:md-mapper-0.1.a8ac39.jar:lib/gson-2.2.4.jar:lib/hamcrest-core-1.1.jar:junit-4.10.jar:lib/log4j-1.2.17.jar:lib/Saxon-HE-9.5.1-4.jar
> nl.mpi.mdmapper.Main config=/home/olof/5.4/config.xml 14:04:31,343
> INFO  Main - Processing files
> in /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2. 14:04:31,475 INFO
> FileProcessor -
> Processing: /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2/SND0963-001.xml
> 14:04:32,039 INFO  FileProcessor -
> Processing: /home/olof/5.4/md-mapping/testfiles/ddi-1.2.2/SND0921-001.xml
> 14:04:32,425 INFO  Main - 2 records mapped; 0 records caused error(s).
> 
> On your system your classpath should already have these globaly but I
> get the impressin by this build these included libraries should be
> included via the jar-file manifest? Can you fix the compile so the
> jar manifest have the correct classpath?
> 
> Best regards,
> Olof
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/

**Comment by borsna** [comment]
Hi Lari and Kees Jan,
The run-mapper script gave me a hint but this method of giving the class-path using -cp does not work for me.
I did a modified version of `run-mapper.sh` witch does work for me:

```
#!/bin/bash

# Script to execute the mapper. See README.txt for information.

JAR=md-mapper-0.1.a8ac39.jar

y=.
for x in lib/*.jar ; do
  y=${y}:${x}
done

nice java -classpath ${y}:${JAR} nl.mpi.mdmapper.Main mapper_version=0.1.a8ac39 $*
```

If this works for you perhaps we could use this as a fix?

**Comment by borsna** [comment]
Just found out if -jar is used; classpath set via -cp/-classpath is ignored so i think this was the issue.
Skipping -jar in the run-script seams to be the the only solution if the manifest in the jar-file don´t do the classpath to the libs.

**Comment by kjvandelooij** [comment]
Hi Lari,

again, thanks for your support. I have already pointed out the difference between the Maven versions early May, so I assumed this was considered.

Cheers, kj

On Wed, 6 Aug 2014 14:37:20 +0200
Lari Lampen notifications@github.com wrote:

> Hi Olof (and KJ), here's one more piece of advice from the sidelines.
> 
> You are right about the classpath being the cause. The reason it
> works for KJ but not for you is your different version of Maven. The
> jar plugin has been changed between Maven 2 and Maven 3. The
> run-mapper script adds all the jar files in lib/ to the classpath
> manually, so it works as long as the manifest contains the two
> entries . and md-mapper-0.1.a8ac39.jar, which it does if you build
> with Maven 2.2 but does not when using Maven >= 3.
> 
> Probably the best idea would be to target Maven 3 from now on, and to
> make the pom file set the manifest with all the relevant jar files so
> that none of that is done in the script. But of course that's for you
> guys, especially KJ, to decide.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kees Jan van de Looij
Max Planck Institute for Psycholinguistics, Nijmegen, the Netherlands
tel. +31-(0)24-3521-478 | http://www.mpi.nl/
